### ISSUE TITLE
why only structs?

### ISSUE THREAD

**Issue by mvolkmann** [HuangRunHua/wwdc23-code-notes#2]
Thank you so much for sharing this!
Are there reasons why you chose to limit this to structs instead of also allowing it to be used on classes?

**Comment by HuangRunHua** [comment]
Hi there, In fact, there is no reason. My original idea of ​​writing StructInit was just to share the joy of writing my own swift marcos with others. I share wwdc-related content on the medium platform, and one of the articles includes structinit, and this program is just a supplement to the article.https://betterprogramming.pub/use-swift-macros-to-initialize-a-structure-516728c5fb49Sent from my iPhoneOn Jun 17, 2023, at 00:14, Mark Volkmann ***@***.***> wrote:﻿
Thank you so much for sharing this!
Are there reasons why you chose to limit this to structs instead of also allowing it to be used on classes?
